workflows:
  react-native-workflow:
    name: React Native Workflow
    environment:
      vars:
        REACT_NATIVE_ENV: production
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Install CocoaPods
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "No Podfile found in root folder."
            exit 1
          fi
      - name: Build iOS
        script: xcodebuild -workspace Sunsip.xcworkspace -scheme Sunsip -sdk iphoneos -configuration Release build
