workflows:
  react-native-workflow:
    name: React Native Workflow
    environment:
      vars:
        REACT_NATIVE_ENV: production
    scripts:
      - name: Install and configure rbenv
        script: |
          brew install rbenv
          rbenv init
          eval "$(rbenv init -)"
          rbenv install 3.1.3 -s
          rbenv global 3.1.3
          ruby --version
      - name: Install drb gem
        script: |
          gem install drb -v 2.0.6
      - name: Install CocoaPods
        script: |
          sudo gem install cocoapods
      - name: Install dependencies
        script: npm install
      - name: Add gonativeio-gonative-specs repo manually
        script: pod repo add gonativeio-gonative-specs https://github.com/gonativeio/gonative-specs.git
      - name: Install CocoaPods dependencies
        script: pod install
      - name: Build iOS
        script: xcodebuild -workspace Sunsip.xcworkspace -scheme Sunsip -sdk iphoneos -configuration Release build
