workflows:
  react-native-workflow:
    name: React Native Workflow
    environment:
      vars:
        REACT_NATIVE_ENV: production
    scripts:
      - name: Update Ruby to 3.1.3
        script: |
          brew install rbenv
          rbenv init
          rbenv install 3.1.3 || true
          rbenv global 3.1.3
          export PATH="$HOME/.rbenv/shims:$PATH"
          ruby --version
      - name: Update CocoaPods
        script: |
          gem install drb -v 2.0.6
          sudo gem install cocoapods
      - name: Install dependencies
        script: npm install
      - name: Add gonativeio-gonative-specs repo manually
        script: pod repo add gonativeio-gonative-specs https://github.com/gonativeio/gonative-specs.git
      - name: Install CocoaPods
        script: pod install
      - name: Build iOS
        script: xcodebuild -workspace Sunsip.xcworkspace -scheme Sunsip -sdk iphoneos -configuration Release build
