workflows:
  react-native-workflow:
    name: React Native Workflow
    environment:
      vars:
        REACT_NATIVE_ENV: production
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Install CocoaPods
        script: cd ios && pod install
      - name: Clean build folder
        script: rm -rf ios/build
      - name: Build iOS
        script: npx react-native run-ios --configuration Release
