workflows:
  react-native-workflow:
    name: React Native Workflow
    environment:
      vars:
        REACT_NATIVE_ENV: production
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build project
        script: npx react-native run-ios
